spring.main.allow-bean-definition-overriding=true
spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.embedding.options.model=all-minilm:l6-v2
spring.ai.ollama.chat.options.model=smollm2:360m
spring.ai.ollama.connection-timeout=60s
spring.ai.ollama.read-timeout=60s
logging.level.com.redis.demo.spring.ai=DEBUG
logging.level.org.springframework.ai=DEBUG
spring.ai.vectorstore.pinecone.dimension=384
spring.ai.vectorstore.pinecone.index-name=beers_collection_en

# Milvus 配置
spring.ai.vectorstore.milvus.client.host=192.168.0.220
spring.ai.vectorstore.milvus.client.port=19530
spring.ai.vectorstore.milvus.collection-name=beers_collection_en
spring.ai.vectorstore.milvus.database-name=default
spring.ai.vectorstore.milvus.index-type=IVF_FLAT
spring.ai.vectorstore.milvus.metric-type=IP
spring.ai.vectorstore.milvus.consistency-level=STRONG

# 降低topK值以减少处理时间
topk=5